# Pandas Fundamentals — Student Practice

Complete the following exercises using Pandas. Run the data setup cells first, then write your answers in the code cells provided. All data are fictional.

You may use the datasets `appointments` and `patients` throughout the notebook. Do not modify the original datasets unless a question asks you to.

## Data setup
Run both cells below before starting the exercises. No external files are required.

In [3]:
import pandas as pd

In [5]:
appointments = pd.DataFrame({
    "visit_id": [101,102,103,104,105,106,107,108,109,110,111,112],
    "patient_id": [1,2,3,1,4,5,2,6,7,8,3,9],
    "clinic": ["North","South","North","East","South","East","North","South","East","North","South","East"],
    "visit_type": ["Checkup","Follow-up","Urgent","Follow-up","Checkup","Urgent","Checkup","Follow-up","Urgent","Checkup","Follow-up","Checkup"],
    "wait_minutes": [15,30,55,20,None,45,10,35,60,25,40,None],
    "cost": [120,150,280,140,110,300,120,160,290,130,155,115],
    "completed": [True,True,True,False,True,True,True,True,False,True,True,True],
    "visit_date": ["2026-01-05","2026-01-06","2026-01-07","2026-01-09","2026-01-12","2026-01-14","2026-01-15","2026-01-17","2026-01-20","2026-01-23","2026-01-25","2026-01-27"]
})
appointments

,visit_id,patient_id,clinic,visit_type,wait_minutes,cost,completed,visit_date
0,101,1,North,Checkup,15.0,120,True,2026-01-05
1,102,2,South,Follow-up,30.0,150,True,2026-01-06
2,103,3,North,Urgent,55.0,280,True,2026-01-07
3,104,1,East,Follow-up,20.0,140,False,2026-01-09
4,105,4,South,Checkup,NaN,110,True,2026-01-12
5,106,5,East,Urgent,45.0,300,True,2026-01-14
6,107,2,North,Checkup,10.0,120,True,2026-01-15
7,108,6,South,Follow-up,35.0,160,True,2026-01-17
8,109,7,East,Urgent,60.0,290,False,2026-01-20
9,110,8,North,Checkup,25.0,130,True,2026-01-23
10,111,3,South,Follow-up,40.0,155,True,2026-01-25
11,112,9,East,Checkup,NaN,115,True,2026-01-27

In [7]:
patients = pd.DataFrame({
    "patient_id": [1,2,3,4,5,6,7,8,9],
    "age": [34,51,29,67,45,39,72,26,58],
    "region": ["Metro","Coastal","Metro","Interior","Coastal","Interior","Metro","Coastal","Interior"]
})
patients

   patient_id  age    region
0           1   34     Metro
1           2   51   Coastal
2           3   29     Metro
3           4   67  Interior
4           5   45   Coastal
5           6   39  Interior
6           7   72     Metro
7           8   26   Coastal
8           9   58  Interior

**Exercise 1 — Selection.** Display only the `visit_id`, `clinic`, and `cost` columns.

In [9]:
# Write your code here
appointments[['visit_id','clinic', 'cost']]

    visit_id clinic  cost
0        101  North   120
1        102  South   150
2        103  North   280
3        104   East   140
4        105  South   110
5        106   East   300
6        107  North   120
7        108  South   160
8        109   East   290
9        110  North   130
10       111  South   155
11       112   East   115

**Exercise 2 — Inspection.** How many rows and columns are in `appointments`? Print the answer using Pandas.

In [21]:
# Write your code here
appointments.shape

(12, 8)

**Exercise 3 — Filtering.** Show all appointments at the `South` clinic.

In [29]:
# Write your code here
appointments[appointments['clinic'] == "South"]

,visit_id,patient_id,clinic,visit_type,wait_minutes,cost,completed,visit_date
1,102,2,South,Follow-up,30.0,150,True,2026-01-06
4,105,4,South,Checkup,NaN,110,True,2026-01-12
7,108,6,South,Follow-up,35.0,160,True,2026-01-17
10,111,3,South,Follow-up,40.0,155,True,2026-01-25

**Exercise 4 — Compound filters.** Find appointments with `cost > 150` **and** `completed == True`.

In [31]:
# Write your code here
appointments[(appointments['cost'] > 150) & (appointments['completed'] == True)]

,visit_id,patient_id,clinic,visit_type,wait_minutes,cost,completed,visit_date
2,103,3,North,Urgent,55.0,280,True,2026-01-07
5,106,5,East,Urgent,45.0,300,True,2026-01-14
7,108,6,South,Follow-up,35.0,160,True,2026-01-17
10,111,3,South,Follow-up,40.0,155,True,2026-01-25

**Exercise 5 — Sorting.** Display the three most expensive appointments.

In [159]:
# Write your code here
appointments.sort_values(by = 'cost', ascending = False, inplace = True)
appointments.head(3)

,visit_id,patient_id,clinic,visit_type,wait_minutes,cost,completed,visit_date,cost_category
5,106,5,East,Urgent,45.0,300,True,2026-01-14,High
8,109,7,East,Urgent,60.0,290,False,2026-01-20,High
2,103,3,North,Urgent,55.0,280,True,2026-01-07,High

**Exercise 6 — Missing data.** Count missing values in `wait_minutes`, then calculate the mean wait using observed values.

In [153]:
# Write your code here
appointments['wait_minutes'].isna().sum()

2

In [155]:
appointments['wait_minutes'].mean()

33.5

**Exercise 7 — New column.** Create `cost_category`: `"High"` for cost >= 200, otherwise `"Regular"`. Do not change the original `appointments` object.

In [183]:
# Write your code here
#df['new'] = df['W'] + df['Y']
import pandas as pd
import numpy as np
new_df = appointments.copy()
#new_df
new_df['cost_category'] = np.where(new_df['cost'] >= 200, 'High', 'Regular')
new_df

,visit_id,patient_id,clinic,visit_type,wait_minutes,cost,completed,visit_date,cost_category
0,101,1,North,Checkup,15.0,120,True,2026-01-05,Regular
1,102,2,South,Follow-up,30.0,150,True,2026-01-06,Regular
2,103,3,North,Urgent,55.0,280,True,2026-01-07,High
3,104,1,East,Follow-up,20.0,140,False,2026-01-09,Regular
4,105,4,South,Checkup,NaN,110,True,2026-01-12,Regular
5,106,5,East,Urgent,45.0,300,True,2026-01-14,High
6,107,2,North,Checkup,10.0,120,True,2026-01-15,Regular
7,108,6,South,Follow-up,35.0,160,True,2026-01-17,Regular
8,109,7,East,Urgent,60.0,290,False,2026-01-20,High
9,110,8,North,Checkup,25.0,130,True,2026-01-23,Regular
10,111,3,South,Follow-up,40.0,155,True,2026-01-25,Regular
11,112,9,East,Checkup,NaN,115,True,2026-01-27,Regular

**Exercise 8 — Value counts.** Count the number of appointments of each `visit_type`.

In [187]:
# Write your code here
appointments['visit_type'].value_counts()

visit_type
Checkup      5
Follow-up    4
Urgent       3
Name: count, dtype: int64

**Exercise 9 — Groupby.** Calculate the average `cost` for each `visit_type`, highest average first.

In [193]:
# Write your code here
appointments.groupby('visit_type')

In [21]:
visit_type = appointments.groupby('visit_type')
#appointments.sort_values(by = 'cost', ascending = False, inplace = True)
visit_type.mean('cost').sort_values(by = 'cost', ascending = False)
#visit_type.mean('cost')
#cost_asce = visit_type.mean('cost')
#cost_asce.sort_values(by = 'cost', ascending = False)

            visit_id  patient_id  wait_minutes    cost  completed
visit_type
Urgent        106.00         5.0     53.333333  290.00   0.666667
Follow-up     106.25         3.0     31.250000  151.25   0.750000
Checkup       107.00         4.8     16.666667  119.00   1.000000

**Exercise 10 — Groupby.** For each clinic, calculate the total number of visits and the number of completed visits.

In [55]:
# Write your code here
clinic = appointments.groupby('clinic')
clinic[['clinic', 'completed']].value_counts()
#clinic['completed'].value_counts()

clinic  completed
East    False        2
        True         2
North   True         4
South   True         4
Name: count, dtype: int64

**Exercise 11 — Dates.** Convert `visit_date` to datetime in a copy and extract the day of the week.

In [73]:
# Write your code here
visit_date = appointments.copy()
#visit_date
#date_time = visit_date.groupby('visit_date')
#date_time
#date_time.to_datetime('visit_date')
#pandas.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=False, format=None, exact=<no_default>, unit=None, origin='unix', cache=True)
visit_date['visit_date'] = pd.to_datetime(visit_date['visit_date'])
#visit_date
visit_date['day_of_the_week'] = visit_date['visit_date'].dt.dayofweek
visit_date['name_of_day_of_the_week'] = visit_date['visit_date'].dt.day_name()

visit_date[['visit_date', 'day_of_the_week', 'name_of_day_of_the_week']]

   visit_date  day_of_the_week name_of_day_of_the_week
0  2026-01-05                0                  Monday
1  2026-01-06                1                 Tuesday
2  2026-01-07                2               Wednesday
3  2026-01-09                4                  Friday
4  2026-01-12                0                  Monday
5  2026-01-14                2               Wednesday
6  2026-01-15                3                Thursday
7  2026-01-17                5                Saturday
8  2026-01-20                1                 Tuesday
9  2026-01-23                4                  Friday
10 2026-01-25                6                  Sunday
11 2026-01-27                1                 Tuesday

**Exercise 12 — Merging.** Join appointments to patients. Find all visits by patients aged 60 or older.

In [ ]:
# Write your code here

**Exercise 13 — Patient-level analysis.** Count appointments per patient and find patients with more than one appointment.

In [ ]:
# Write your code here

**Exercise 14 — Pivot.** Build a table with clinics as rows, visit types as columns, and *average cost* as values.

In [ ]:
# Write your code here

**Exercise 15 — Mini challenge.** Identify which clinic has the highest **mean observed wait time**. Report the clinic and value. Explain briefly how missing waits affect your answer.

In [ ]:
# Write your code here

## Additional practice

**Exercise 16 — Region summary.** Merge the appointment and patient tables. For each region, calculate the number of appointments and average appointment cost.

In [ ]:
# Write your code here

**Exercise 17 — Visualization.** Create a bar chart showing the number of appointments at each clinic. Include a title and axis labels.

In [ ]:
# Write your code here

**Exercise 18 — CSV.** Save `appointments` to a CSV file without the index. Read the file back into a new DataFrame, then display its first five rows.

In [ ]:
# Write your code here